### ISSUE TITLE
Creating a data object with custom vectors 

### ISSUE THREAD

**Issue by parkerduckworth** [semi-technologies/weaviate-go-client#36]
Hello!

I noticed in the [Weaviate API docs](https://www.semi.technology/developers/weaviate/current/restful-api-references/objects.html#create-a-data-object-with-custom-vectors) that "`creating a data object with custom vectors will be supporting in the GO client soon`", however I don't see an open issue or PR that address this, and it is a piece of functionality that would be very useful to me.

Do you mind if I implement data object creation with custom vectors, and open an PR?

Thanks!

**Comment by etiennedi** [comment]
Hi @parkerduckworth, thanks for spotting this. We must have forgotten this somehow. We'd be happy to accept a small PR that adds a `WithVector(vec []float32)` method to the [`data.Creator`](https://github.com/semi-technologies/weaviate-go-client/blob/a535da0e88519bbdb961fa90a90bdfe02440d5c3/v2/weaviate/data/creator.go#L19-L24). Please also make sure to add a [new test](https://github.com/semi-technologies/weaviate-go-client/blob/master/v2/test/data/data_test.go). @antas-marcin can also help if there are any questions. Thank you!

**Comment by parkerduckworth** [comment]
@etiennedi Great, thanks! Opened up a PR.
